name: Teste
version: '1.0-SNAPSHOT'
main: teste.teste.Main
api-version: 1.18
commands:
  DIA:
    description: Coloca de dia.
    usage: /DIA
  CURAR:
    description: Cura um jogador.
    usage: /CURAR
  GM:
    description: Alterna o modo de jogo entre criativo e sobrevivencia.
    usage: /GM
  CHUVA:
    description: Faz parar ou comecar a chuver.
    usage: /CHUVA
  KIT:
    usage: /KIT